# 服务端口
server:
  port: 8201
#服务名
spring:
  application:
    name: service-hosp
  #环境设置：dev、test、prod
  profiles:
    active: dev
  #MySQL数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:13306/yygh_hosp?characterEncoding=utf-8
  #返回JSON的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://hadoop100:27017/test
# nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl